spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: 99679450Kk
  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate.ddl-auto: create
  application:
    name: login
server:
  port: 8088
usercontroller:
  messages:
    exception1: User Not Found
    exception2: Sucessfully Created
    exception3: please fill in username and password
    exception4: user username not found
    exception5: Invalid Login.Please check your username and password

kafka:
  ipAddress: 172.23.239.197:9092
  groupId: group_id54
  listeningTopic: user
  containerFactory: kafkaUserListenerContainerFactory